### ISSUE TITLE
todo things1

### ISSUE THREAD

**Issue by rovast** [rovast/gitlab-webhook#1]
第一版的使用是及其简单的实现，运行一段时间后，发现下述问题需要解决

- [x] 提供 UI 自助操作页面。进一步释放手动运维
- [x] 按需 `npm install`。当有新的依赖添加进来后，先安装依赖，再 build:dist
- [x] 并发处理 command。当前是串行处理，需要做并发处理

**Comment by rovast** [comment]
1. UI 暂缓
2. 通过 `npm install --prefer-offline --no-audit --progress=false && npm run build:prod`，每次安装依赖
3. 并发默认支持
